In [1]:
# Cell 1 - Install/imports + env load
# Fresh venv? Uncomment once:
# %pip install -r requirements.txt

import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
from dotenv import load_dotenv

REPO_ROOT = Path.cwd()
SRC_PATH = REPO_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from exa_demo.artifacts import ExperimentArtifactWriter
from exa_demo.cache import SqliteCacheStore
from exa_demo.client import build_exa_payload as _build_exa_payload
from exa_demo.client import exa_search_people as _exa_search_people
from exa_demo.config import default_config, default_pricing, load_runtime_state
from exa_demo.cost_model import estimate_cost_from_pricing as _estimate_cost_from_pricing_base
from exa_demo.evaluation import DEFAULT_RELEVANCE_KEYWORDS, evaluate_batch_queries, load_benchmark_queries
from exa_demo.reporting import (
    build_before_after_report,
    build_cost_projections,
    build_qualitative_notes,
    recommendation,
    summarize_failure_taxonomy,
    write_comparison_markdown,
)
from exa_demo.safety import extract_preview as _module_extract_preview
from exa_demo.safety import redact_text as _module_redact_text

load_dotenv()  # loads .env from notebook working directory

runtime = load_runtime_state()
EXA_API_KEY = runtime.exa_api_key
EXA_SMOKE_NO_NETWORK = runtime.smoke_no_network
RUN_ID = runtime.run_id

if EXA_SMOKE_NO_NETWORK:
    print("Mode: smoke (no network)")
else:
    print("Mode: live Exa API")

print(f"RUN_ID: {RUN_ID}")

Mode: live Exa API
RUN_ID: 20260310T142448Z

In [2]:
# Cell 2 - Config

CONFIG = default_config()
PRICING = default_pricing()

# Optional before/after baseline comparison for Cell 9; leave blank to skip.
CONFIG["compare_to_run_id"] = ""
CONFIG["compare_base_dir"] = "experiments"

print(json.dumps(CONFIG, indent=2))

{
  "exa_endpoint": "https://api.exa.ai/search",
  "search_type": "auto",
  "category": "people",
  "num_results": 5,
  "user_location": "US",
  "use_text": false,
  "use_highlights": true,
  "highlights_per_url": 1,
  "highlight_num_sentences": 2,
  "use_summary": false,
  "include_domains": [],
  "exclude_domains": [],
  "moderation": true,
  "redact_emails_phones": true,
  "budget_cap_usd": 7.5,
  "sqlite_path": "exa_cache.sqlite",
  "cache_ttl_hours": 720,
  "max_supported_results_for_estimate": 100
}

In [3]:
# Cell 3 - Exa call wrapper

def _estimate_cost_from_pricing(payload: Dict[str, Any], num_results: int) -> float:
    return _estimate_cost_from_pricing_base(
        payload,
        num_results,
        PRICING,
        int(CONFIG["max_supported_results_for_estimate"]),
    )


def redact_text(s: Optional[str]) -> Optional[str]:
    return _module_redact_text(s, enabled=CONFIG.get("redact_emails_phones", True))


def extract_preview(result: Dict[str, Any], max_chars: int = 280) -> str:
    return _module_extract_preview(
        result,
        max_chars=max_chars,
        redact_enabled=CONFIG.get("redact_emails_phones", True),
    )


def build_exa_payload(query: str, *, num_results: Optional[int] = None) -> Dict[str, Any]:
    return _build_exa_payload(query, CONFIG, num_results=num_results)


def exa_search_people(query: str, *, num_results: Optional[int] = None):
    return _exa_search_people(
        query,
        config=CONFIG,
        pricing=PRICING,
        exa_api_key=EXA_API_KEY,
        smoke_no_network=EXA_SMOKE_NO_NETWORK,
        run_id=RUN_ID,
        cache_store=_cache_store(),
        num_results=num_results,
    )

In [4]:
# Cell 4 - Cache wrapper (sqlite) + run-scoped budget enforcement


def _cache_store() -> SqliteCacheStore:
    return SqliteCacheStore(CONFIG["sqlite_path"], CONFIG["cache_ttl_hours"])


def ledger_summary(run_id: Optional[str] = None) -> pd.DataFrame:
    return _cache_store().ledger_summary(run_id=run_id)


def spend_so_far(run_id: Optional[str] = None) -> Dict[str, float]:
    return _cache_store().spend_so_far(run_id=run_id)


ARTIFACT_WRITER = ExperimentArtifactWriter(
    run_id=RUN_ID,
    config=CONFIG,
    pricing=PRICING,
)

print("Cache ready:", CONFIG["sqlite_path"])
print("Experiment artifacts:", ARTIFACT_WRITER.artifact_dir)
print("Run metrics:", spend_so_far(run_id=RUN_ID))
print("All-time metrics:", spend_so_far())

Cache ready: exa_cache.sqlite
Experiment artifacts: experiments\20260310T142448Z
Run metrics: {'request_count': 0, 'cache_hits': 0, 'uncached_calls': 0, 'spent_usd': 0.0, 'avg_cost_per_uncached_query': 0.0}
All-time metrics: {'request_count': 309, 'cache_hits': 233, 'uncached_calls': 76, 'spent_usd': 0.805, 'avg_cost_per_uncached_query': 0.010592}

In [5]:
# Cell 5 - Single query demo

demo_query = "Florida property insurance attorney hurricane Ian appraisal dispute site:linkedin.com"
resp_demo, meta_demo = exa_search_people(demo_query, num_results=CONFIG["num_results"])

print("Single-query demo")
print("  run_id:", RUN_ID)
print("  cache_hit:", meta_demo.cache_hit)
print("  estimated_cost_usd:", meta_demo.estimated_cost_usd)
print("  actual_cost_usd:", meta_demo.actual_cost_usd)
print("  request_id:", meta_demo.request_id)

results_demo = resp_demo.get("results", []) if isinstance(resp_demo, dict) else []
rows_demo = []
for result in results_demo[: int(CONFIG["num_results"])]:
    rows_demo.append(
        {
            "title": redact_text(result.get("title")),
            "url": result.get("url"),
            "preview": extract_preview(result, max_chars=280),
            "highlightScores": result.get("highlightScores"),
        }
    )

df_demo = pd.DataFrame(rows_demo)
print("Rows returned:", len(df_demo))
df_demo

Single-query demo
  run_id: 20260310T142448Z
  cache_hit: True
  estimated_cost_usd: 0.01
  actual_cost_usd: 0.01
  request_id: 4ba4681290c69b1e0269bdb256e75d88
Rows returned: 5

,title,url,preview,highlightScores
0,Amy Boggs | Florida Property Insurance Attorney,https://linkedin.com/in/amy-boggs,practice focuses on the following insurance c...,[0.75]
1,Steven Venook | 25 yrs Exp Disputed Insurance ...,https://linkedin.com/in/claimexpert,"IES: Water damage, Mold damage, Lightning Dama...",[0.51953125]
2,Derrick Martin | Property & Casualty Claims Pr...,https://linkedin.com/in/derrick-martin-1b981b146,"ed carrier in mediation, appraisal, and other ...",[0.734375]
3,Douglas Anderson | Independent Insurance Adjus...,https://linkedin.com/in/douglas-anderson-89a924ba,.2018 - Present - Dispute resolution appraisal...,[0.515625]
4,James C. Murphy | Licensed Public Adjuster (FL...,https://linkedin.com/in/jcmadjuster,"Specialize in hurricane, wind, water, fire, a...",[0.7578125]

In [6]:
# Cell 6 - Batch query test suite (insurance / CAT)

# Swap this list only; the rest of the notebook will continue to work.
TEST_QUERIES = load_benchmark_queries()
RELEVANCE_KEYWORDS = list(DEFAULT_RELEVANCE_KEYWORDS)

df_batch = evaluate_batch_queries(
    TEST_QUERIES,
    search_people=exa_search_people,
    num_results=int(CONFIG["num_results"]),
    relevance_keywords=RELEVANCE_KEYWORDS,
    redact_text=redact_text,
    extract_preview=extract_preview,
    record_query=ARTIFACT_WRITER.record_query,
)

print(f"Batch queries executed: {len(df_batch)}")
df_batch

Batch queries executed: 15

,query,cache_hit,request_hash,request_id,resolved_search_type,est_cost_usd,actual_cost_usd,top_title,top_url,top_preview,linkedin_present,relevance_keywords_present,result_count
0,forensic engineer wind damage expert witness F...,True,9479cca8a0532af7bb615b74d78d926d2fed81c5b56d2d...,694098818f0e5ec9b32bbeaa929ca35d,neural,0.01,0.01,David Cowheard | Forensic & Dispute Services P...,https://linkedin.com/in/david-cowheard-a14b2314,witness testimony in the areas of insurance c...,True,True,5
1,building envelope consultant moisture intrusio...,True,feab3f2d9e6be9ba9f0305b8040beca9b4800729f9a60e...,b1cdb650349ec3b8cce2fa93c38e4e77,neural,0.01,0.01,Don Williams | Principal at Moisture Intrusion...,https://linkedin.com/in/don-williams-94272611,clients in preventing future water intrusion ...,True,True,5
2,forensic accountant business interruption insu...,True,9ae70d6e4df2eab6f4272c02ffb4a135b59f20d879d4be...,ed731224ca1f80f1a616c702814835da,neural,0.01,0.01,John W. Foley | Forensic Accountant & Expert W...,https://linkedin.com/in/john-w-foley-31038571,"a qualified expert witness, I’ve testified or...",True,True,5
3,meteorologist hurricane wind field expert witn...,True,160918a87d12e8f607823932476502f5abb07f0199d4c3...,c516de63248f810d72fad526099eeabf,neural,0.01,0.01,Craig Setzer | Chief Meteorologist Royal Carib...,https://linkedin.com/in/craig-setzer-ccm-03095...,igation experience in matters related to meteo...,True,True,5
4,fire origin and cause investigator expert witn...,True,8dffcdd2009446bd9d36955d011c4e7e2f08efb0f5bf1d...,531d1d29806dbbf468b3c977970b34ff,neural,0.01,0.01,Michael Whedon | Fire and Explosion Investigator,https://linkedin.com/in/michael-whedon-85a639b5,"to insurance companies, private industry and ...",True,True,5
5,policyholder attorney bad faith property insur...,True,2d3609123d0930ea3f8685642f5cae15c6d016c17a314f...,de61de2cdafa7c0525a14e4280f60aff,neural,0.01,0.01,Corey Harris | Attorney at Merlin Law Group,https://linkedin.com/in/corey-harris-345b7981,trial attorney exclusively representing polic...,True,True,5
6,Texas hail damage property insurance attorney ...,True,a59148100b833ef1336a9f8fbcc5bd8e090ba57b166357...,78fcd155dd4626630fd027546084ab64,neural,0.01,0.01,David Rocha | Claims Examiner,https://linkedin.com/in/david-rocha-13997217,"settlement of wind and hail property losses, ...",True,True,5
7,insurance appraisal umpire property claims Flo...,True,646134153b552a43b9a23bbb04934156bd13f4219c8aff...,6587a1fef8109eec3bf2a34cee4a225b,neural,0.01,0.01,"Michael Ruskin | Umpire, Insurance Appraiser, ...",https://linkedin.com/in/michael-ruskin-09214115,". Offices located in Florida, North Carolina, ...",True,True,5
8,licensed public adjuster large loss hurricane ...,True,08dc7430563e9fb91f0083962d024633e4ae8deec0c830...,b136d7ad782ffd2b129511b731da2cb6,neural,0.01,0.01,Frank Altieri | The Policyholders’ Adjuster,https://linkedin.com/in/frank-altieri-5b7bb743,Altieri Insurance Consultants is a nationwide ...,True,True,5
9,Xactimate trainer estimator large loss consult...,True,8643eb6667daa7fd328d7f617275959b17999d0aa746fe...,e1255b0c2bf87afc31da41f632038450,neural,0.01,0.01,Weston Faulkner | Large Loss Adjuster / Estima...,https://linkedin.com/in/weston-faulkner-6b4b5a1a,knowledge in Xactimate Estimating Software. T...,True,True,5
10,claims consultant catastrophe response litigat...,True,a3b8c8ae647722222bd69a2ff273583ba4b93a80f4040e...,c7e15a45d819e81881d5b73c94a0d59a,neural,0.01,0.01,Courtney R. | Residential & Commercial Propert...,https://linkedin.com/in/courtney-r-1a50a7196,irected litigation strategy with external coun...,True,True,5
11,insurance coverage expert witness former adjus...,True,21d7ab9a86969d435ec808bcf5bd67b2b9a7a774b8b3a7...,9443ec4be6713bbd19930ed7c9cc6c6c,neural,0.01,0.01,Rick Hammond | Providing consultation and expe...,https://linkedin.com/in/rick-hammond-9aa683a,as legal counsel and a trial attorney on matt...,True,True,5
12,water mitigation IICRC expert witness insuranc...,True,4d0fd173ad3ce12790a7964394c7679987e8cc8ed71a2d...,f9d51f4dc55083f65345b4dfb14a7e4e,neural,0.01,0.01,Kenan Petrash | Sr. Property Claims Resolution...,https://linkedin.com/in/kcpetrash,Restoration Technician Licensed; Intricate kn...,True,True,5
13,roofing consultant wind uplift tile roof exper...,True,9324debdedaf85113a515f7528119dd7250f6a17d800f2...,8dc16ebe6aaf3c7238949bbf4cb8f83d,neural,0.01,0.01,Blake Shatto | Forensic Engineering Consultant...,https://linkedin.com/in/blake-shatto,"Inspector (Residential & Commercial Roofs, Wi...",True,True,5
14,civil engineer structural damage assessment hu...,True,08a79ab21308294e1408941d6c079e4656614d54fc7950...,e97bb773155156155dce59432c2f1cc9,neural,0.01,0.01,"Richard Harb | Harb Engineering & Consulting, ...",https://linkedin.com/in/richard-harb-pe-3905a126,"assessment, forensic investigations, expert w...",True,True,5

In [7]:
# Cell 7 - Summary table + qualitative notes

summary = spend_so_far(run_id=RUN_ID)
summary_all = spend_so_far()

df_ledger_run = ledger_summary(run_id=RUN_ID)

df_summary = pd.DataFrame([{
    "run_id": RUN_ID,
    "request_count": summary["request_count"],
    "cache_hits": summary["cache_hits"],
    "uncached_calls": summary["uncached_calls"],
    "spent_usd": summary["spent_usd"],
    "avg_cost_per_uncached_query": summary["avg_cost_per_uncached_query"],
}])

taxonomy = summarize_failure_taxonomy(df_batch)
df_taxonomy = pd.DataFrame([
    {
        "relevance_score_mean": taxonomy["relevance_score_mean"],
        "credibility_score_mean": taxonomy["credibility_score_mean"],
        "actionability_score_mean": taxonomy["actionability_score_mean"],
        "confidence_score_mean": taxonomy["confidence_score_mean"],
        "failure_rate": taxonomy["failure_rate"],
        "queries_with_failures": taxonomy["queries_with_failures"],
        "total_queries": taxonomy["total_queries"],
    }
])

print(f"Request count: {summary['request_count']}")
print(f"Cache hits vs uncached calls: {summary['cache_hits']} vs {summary['uncached_calls']}")
print(f"Spent so far (run {RUN_ID}): ${summary['spent_usd']:.4f}")
print(f"Avg cost per uncached query: ${summary['avg_cost_per_uncached_query']:.4f}")
print(f"All-time spend across runs: ${summary_all['spent_usd']:.4f}")

print("\nSummary table")
try:
    print(df_summary.to_markdown(index=False))
except Exception:
    print(df_summary)

print("\nTaxonomy scorecard")
try:
    print(df_taxonomy.to_markdown(index=False))
except Exception:
    print(df_taxonomy)

print("\nFailure reason counts")
print(json.dumps(taxonomy["failure_reason_counts"], indent=2, sort_keys=True))

qualitative_notes = build_qualitative_notes(
    df_batch,
    CONFIG,
    smoke_no_network=EXA_SMOKE_NO_NETWORK,
)

print("\nQualitative notes")
for note in qualitative_notes:
    print("-", note)

review_cols = [
    "query",
    "top_title",
    "top_url",
    "top_preview",
    "linkedin_present",
    "relevance_keywords_present",
    "relevance_score",
    "credibility_score",
    "actionability_score",
    "confidence_score",
    "primary_failure_reason",
    "cache_hit",
    "actual_cost_usd",
    "est_cost_usd",
]

df_batch[review_cols]

Request count: 16
Cache hits vs uncached calls: 16 vs 0
Spent so far (run 20260310T142448Z): $0.0000
Avg cost per uncached query: $0.0000
All-time spend across runs: $0.8050

Summary table
| run_id           |   request_count |   cache_hits |   uncached_calls |   spent_usd |   avg_cost_per_uncached_query |
|:-----------------|----------------:|-------------:|-----------------:|------------:|------------------------------:|
| 20260310T142448Z |              16 |           16 |                0 |           0 |                             0 |

Qualitative notes
- Relevance-keyword signal rate: 100%.
- LinkedIn profile signal present in: 100% of queries.
- Average results returned per query: 5.0 (num_results=5).
- Text is disabled: cheaper baseline; highlights are usually enough for triage.
- Summary is disabled (recommended baseline for low-cost evaluation).

,query,top_title,top_url,top_preview,linkedin_present,relevance_keywords_present,cache_hit,actual_cost_usd,est_cost_usd
0,forensic engineer wind damage expert witness F...,David Cowheard | Forensic & Dispute Services P...,https://linkedin.com/in/david-cowheard-a14b2314,witness testimony in the areas of insurance c...,True,True,True,0.01,0.01
1,building envelope consultant moisture intrusio...,Don Williams | Principal at Moisture Intrusion...,https://linkedin.com/in/don-williams-94272611,clients in preventing future water intrusion ...,True,True,True,0.01,0.01
2,forensic accountant business interruption insu...,John W. Foley | Forensic Accountant & Expert W...,https://linkedin.com/in/john-w-foley-31038571,"a qualified expert witness, I’ve testified or...",True,True,True,0.01,0.01
3,meteorologist hurricane wind field expert witn...,Craig Setzer | Chief Meteorologist Royal Carib...,https://linkedin.com/in/craig-setzer-ccm-03095...,igation experience in matters related to meteo...,True,True,True,0.01,0.01
4,fire origin and cause investigator expert witn...,Michael Whedon | Fire and Explosion Investigator,https://linkedin.com/in/michael-whedon-85a639b5,"to insurance companies, private industry and ...",True,True,True,0.01,0.01
5,policyholder attorney bad faith property insur...,Corey Harris | Attorney at Merlin Law Group,https://linkedin.com/in/corey-harris-345b7981,trial attorney exclusively representing polic...,True,True,True,0.01,0.01
6,Texas hail damage property insurance attorney ...,David Rocha | Claims Examiner,https://linkedin.com/in/david-rocha-13997217,"settlement of wind and hail property losses, ...",True,True,True,0.01,0.01
7,insurance appraisal umpire property claims Flo...,"Michael Ruskin | Umpire, Insurance Appraiser, ...",https://linkedin.com/in/michael-ruskin-09214115,". Offices located in Florida, North Carolina, ...",True,True,True,0.01,0.01
8,licensed public adjuster large loss hurricane ...,Frank Altieri | The Policyholders’ Adjuster,https://linkedin.com/in/frank-altieri-5b7bb743,Altieri Insurance Consultants is a nationwide ...,True,True,True,0.01,0.01
9,Xactimate trainer estimator large loss consult...,Weston Faulkner | Large Loss Adjuster / Estima...,https://linkedin.com/in/weston-faulkner-6b4b5a1a,knowledge in Xactimate Estimating Software. T...,True,True,True,0.01,0.01
10,claims consultant catastrophe response litigat...,Courtney R. | Residential & Commercial Propert...,https://linkedin.com/in/courtney-r-1a50a7196,irected litigation strategy with external coun...,True,True,True,0.01,0.01
11,insurance coverage expert witness former adjus...,Rick Hammond | Providing consultation and expe...,https://linkedin.com/in/rick-hammond-9aa683a,as legal counsel and a trial attorney on matt...,True,True,True,0.01,0.01
12,water mitigation IICRC expert witness insuranc...,Kenan Petrash | Sr. Property Claims Resolution...,https://linkedin.com/in/kcpetrash,Restoration Technician Licensed; Intricate kn...,True,True,True,0.01,0.01
13,roofing consultant wind uplift tile roof exper...,Blake Shatto | Forensic Engineering Consultant...,https://linkedin.com/in/blake-shatto,"Inspector (Residential & Commercial Roofs, Wi...",True,True,True,0.01,0.01
14,civil engineer structural damage assessment hu...,"Richard Harb | Harb Engineering & Consulting, ...",https://linkedin.com/in/richard-harb-pe-3905a126,"assessment, forensic investigations, expert w...",True,True,True,0.01,0.01

In [8]:
# Cell 8 - Cost estimate + projections

observed_spent = float(summary.get("spent_usd", 0.0))
projections = build_cost_projections(summary, config=CONFIG, pricing=PRICING)

print(f"Spent so far (run {RUN_ID}): ${observed_spent:.4f}")
print(f"Projection basis: {projections['projection_basis']}")
print(f"Projected cost for 100 queries:   ${projections['projected_100_queries_usd']:.4f}")
print(f"Projected cost for 1,000 queries: ${projections['projected_1000_queries_usd']:.4f}")
print(f"Projected cost for 10,000 queries:${projections['projected_10000_queries_usd']:.4f}")

pd.DataFrame([projections])

Spent so far (run 20260310T142448Z): $0.0000
Projection basis: estimated_from_current_config
Projected cost for 100 queries:   $1.0000
Projected cost for 1,000 queries: $10.0000
Projected cost for 10,000 queries:$100.0000

,projection_basis,unit_cost_usd,projected_100_queries_usd,projected_1000_queries_usd,projected_10000_queries_usd
0,estimated_from_current_config,0.01,1.0,10.0,100.0

In [9]:
# Cell 9 - Decision rubric + recommendation integration points

RUBRIC = {
    "Search quality (people relevance)": "Do results return the right categories of professionals for CAT-loss / claim-dispute work?",
    "Coverage": "Does it find credible candidates beyond obvious first-page names?",
    "Evidence quality": "Are highlights/snippets sufficient for triage without defaulting to full text?",
    "Latency": "Is response time acceptable for analyst workflows?",
    "Cost": "Is unit cost predictable and within budget at projected volumes?",
    "Safety/compliance": "Can outputs stay public/professional only (no doxxing/contact harvesting)?",
    "Repeatability": "Do cached reruns reliably reproduce behavior without rebilling?",
}

print("Decision rubric")
for criterion, prompt in RUBRIC.items():
    print(f"- [ ] {criterion}: {prompt}")


rec = recommendation(
    summary,
    df_batch,
    run_id=RUN_ID,
    budget_cap_usd=float(CONFIG["budget_cap_usd"]),
    smoke_no_network=EXA_SMOKE_NO_NETWORK,
)
print("\nRecommendation output")
print(json.dumps(rec, indent=2))

compare_to_run_id = str(CONFIG.get("compare_to_run_id") or "").strip()
comparison_report = None
comparison_markdown_path = None
if compare_to_run_id:
    compare_base_dir = Path(str(CONFIG.get("compare_base_dir") or "experiments"))
    compare_run_dir = compare_base_dir / compare_to_run_id
    comparison_report = build_before_after_report(
        compare_run_dir,
        after_run_id=RUN_ID,
        after_summary_metrics=summary,
        after_batch_df=df_batch,
        after_recommendation=rec,
    )
    comparison_markdown_path = write_comparison_markdown(ARTIFACT_WRITER.artifact_dir, comparison_report)
    print("\nBefore/after comparison")
    print(json.dumps(comparison_report, indent=2))
else:
    print("\nBefore/after comparison skipped (set CONFIG['compare_to_run_id'] to enable).")

summary_extra = {
    "summary_all": summary_all,
    "taxonomy": taxonomy,
}
if comparison_report is not None:
    summary_extra["comparison"] = comparison_report

summary_path = ARTIFACT_WRITER.write_summary(
    summary,
    projections=projections,
    recommendation_data=rec,
    batch_df=df_batch,
    qualitative_notes=qualitative_notes,
    extra=summary_extra,
)
print("\nExperiment artifacts written to:", ARTIFACT_WRITER.artifact_dir)
print("Summary artifact:", summary_path)
if comparison_markdown_path is not None:
    print("Comparison markdown:", comparison_markdown_path)

Decision rubric
- [ ] Search quality (people relevance): Do results return the right categories of professionals for CAT-loss / claim-dispute work?
- [ ] Coverage: Does it find credible candidates beyond obvious first-page names?
- [ ] Evidence quality: Are highlights/snippets sufficient for triage without defaulting to full text?
- [ ] Latency: Is response time acceptable for analyst workflows?
- [ ] Cost: Is unit cost predictable and within budget at projected volumes?
- [ ] Safety/compliance: Can outputs stay public/professional only (no doxxing/contact harvesting)?
- [ ] Repeatability: Do cached reruns reliably reproduce behavior without rebilling?

Recommendation output
{
  "run_id": "20260310T142448Z",
  "headline_recommendation": "Integrate (with human review and budget guards)",
  "observed_relevance_rate": 1.0,
  "observed_linkedin_rate": 1.0,
  "avg_cost_per_uncached_query_usd": 0.0,
  "budget_cap_usd": 7.5,
  "safety_guardrails": [
    "Public/professional info only",
    "No address hunting or contact harvesting",
    "Keep redaction enabled for displayed snippets",
    "Human review required before operational use"
  ],
  "integration_points": [
    {
      "workflow": "Expert/professional discovery",
      "value": "Find candidate experts and collect source URLs + short relevance snippets for analyst review.",
      "safe_pattern": "Query by role + peril + jurisdiction; keep outputs to title/url/highlights by default."
    },
    {
      "workflow": "Consultant/witness context enrichment",
      "value": "When reports name professionals, quickly pull public bios/publications for context.",
      "safe_pattern": "Search by name + role + insurance/litigation terms; do not harvest personal contact data."
    },
    {
      "workflow": "Claim dispute research triage",
      "value": "Identify relevant disciplines (forensic engineer, meteorologist, accountant, etc.) fast.",
      "safe_pattern": "Use highlights-on/text-off baseline; selectively deepen only shortlisted results."
    }
  ],
  "next_tuning_moves": [
    "Keep highlights on, text off, summary off, num_results=5 for baseline cost testing.",
    "Use include_domains only when you need tighter source control.",
    "Enable text/summary only in second-pass review workflows."
  ]
}

Experiment artifacts written to: experiments\20260310T142448Z
Summary artifact: experiments\20260310T142448Z\summary.json

In [10]:
EXPERIMENTAL_MODE = False

EXPERIMENTS = {
    "test_param_variants": True,
    "test_second_pass": True,
    "test_structured_output": True,
    "test_domain_workflows": False,
}

In [11]:
EXPERIMENTAL_MODE = False

EXPERIMENTS = {
    "test_param_variants": True,
    "test_second_pass": True,
    "test_structured_output": True,
    "test_domain_workflows": False,
}

TEST_QUERY = "Find public experts relevant to hurricane damage dispute in Florida"
TEST_ROLE_QUERY = "Find Florida public adjusters, forensic engineers, and meteorologists who discuss hurricane damage claims"

BASELINE_PARAMS = {
    "num_results": 5,
    "highlights": False,
    "text": False,
    "summary": False,
    "include_domains": None,
    "exclude_domains": None,
}

In [12]:
from pprint import pprint

def run_experiment_search(
    query,
    num_results=5,
    highlights=False,
    text=False,
    summary=False,
    include_domains=None,
    exclude_domains=None,
):
    """
    Example direct-client adapter.
    Adjust method/argument names if your installed SDK differs.
    """

    kwargs = {
        "query": query,
        "num_results": num_results,
    }

    if include_domains:
        kwargs["include_domains"] = include_domains
    if exclude_domains:
        kwargs["exclude_domains"] = exclude_domains

    # You may need to adjust the flags below to match your SDK / notebook logic.
    if highlights:
        kwargs["highlights"] = True
    if text:
        kwargs["text"] = True
    if summary:
        kwargs["summary"] = True

    return exa.search_and_contents(**kwargs)

In [13]:
import json
from typing import Any

def _safe_get(obj: Any, key: str, default=None):
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)

def extract_items(raw):
    """
    Tries a few common patterns:
    - list
    - dict with 'results'
    - object with '.results'
    """
    if raw is None:
        return []

    if isinstance(raw, list):
        return raw

    if isinstance(raw, dict):
        if "results" in raw:
            return raw["results"]
        return [raw]

    if hasattr(raw, "results"):
        return raw.results

    return [raw]

def normalize_result(item):
    title = _safe_get(item, "title") or _safe_get(item, "name") or "Untitled"
    url = _safe_get(item, "url") or _safe_get(item, "source") or ""
    score = _safe_get(item, "score") or _safe_get(item, "relevance_score") or None
    published_date = _safe_get(item, "published_date") or _safe_get(item, "publishedDate") or None
    author = _safe_get(item, "author") or None

    text_value = _safe_get(item, "text") or ""
    summary_value = _safe_get(item, "summary") or ""
    highlights_value = _safe_get(item, "highlights") or []

    if isinstance(highlights_value, str):
        highlights_value = [highlights_value]

    return {
        "title": title,
        "url": url,
        "score": score,
        "published_date": published_date,
        "author": author,
        "summary": summary_value,
        "text_preview": text_value[:500] if text_value else "",
        "highlights": highlights_value[:3],
    }

def preview_results(raw, max_items=3):
    items = extract_items(raw)
    print(f"Total items: {len(items)}")
    for i, item in enumerate(items[:max_items], start=1):
        norm = normalize_result(item)
        print(f"\n--- Result {i} ---")
        print("Title:", norm["title"])
        print("URL:", norm["url"])
        print("Score:", norm["score"])
        print("Published:", norm["published_date"])
        print("Author:", norm["author"])
        if norm["summary"]:
            print("Summary:", norm["summary"][:300])
        if norm["highlights"]:
            print("Highlights:", norm["highlights"])
        if norm["text_preview"]:
            print("Text preview:", norm["text_preview"][:300])

In [14]:
if EXPERIMENTAL_MODE:
    baseline_raw = run_experiment_search(
        query=TEST_QUERY,
        num_results=BASELINE_PARAMS["num_results"],
        highlights=BASELINE_PARAMS["highlights"],
        text=BASELINE_PARAMS["text"],
        summary=BASELINE_PARAMS["summary"],
        include_domains=BASELINE_PARAMS["include_domains"],
        exclude_domains=BASELINE_PARAMS["exclude_domains"],
    )

    preview_results(baseline_raw, max_items=3)

NameError: name 'exa' is not defined